# Generated by Django 5.2.7 on 2025-10-25 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_artikle_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikle',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2025, 10, 25, 9, 54, 34, 825063)),
        ),
        migrations.AlterField(
            model_name='artikle',
            name='title',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
