# Generated by Django 5.2.7 on 2025-10-25 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_artikle_pub_date_alter_artikle_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.DateField(max_length=50)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='artikle',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2025, 10, 25, 10, 21, 0, 422433)),
        ),
        migrations.AlterField(
            model_name='artikle',
            name='title',
            field=models.CharField(max_length=10, unique=True, unique_for_date='pub_date'),
        ),
        migrations.AddField(
            model_name='artikle',
            name='category',
            field=models.ManyToManyField(to='blog.category'),
        ),
    ]
