# Generated by Django 5.2.7 on 2025-10-25 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_category_alter_artikle_pub_date_alter_artikle_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikle',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2025, 10, 25, 10, 25, 36, 236511)),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
