# Generated by Django 5.2.7 on 2025-10-25 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_artikle_pub_date_alter_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikle',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2025, 10, 25, 10, 52, 16, 345894)),
        ),
    ]
